version: 2
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
- name_template: >-
    {{- .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
      - "ghcr.io/adfinis/potz-holzoepfel-und-zipfelchape:{{ .Tag }}"
      - "ghcr.io/adfinis/potz-holzoepfel-und-zipfelchape:v{{ .Major }}"
      - "ghcr.io/adfinis/potz-holzoepfel-und-zipfelchape:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/adfinis/potz-holzoepfel-und-zipfelchape:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - etc/passwd
