version: '3.7'
services:
  mongodb_container:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hunter2
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  jaeger_aio:
    image: jaegertracing/all-in-one:1.22
    ports:
      - 16686:16686
      - 14268:14268

volumes:
  mongodb_data_container:
